---
title: "Kapitel 5: Schätzen"
author: "Matthias Kohl"
date: "Oktober 2020"
output:
  rmarkdown::html_document:
    theme: united
    highlight: tango
    toc: true
---

```{r, eval=FALSE}
install.packages("BiocManager")
BiocManager::install("Biobase", update = FALSE)
```


```{r, eval=FALSE}
install.packages(c("distrMod", "qqplotr", "RobLox", "gridExtra", "MKinfer", 
                   "ROptEst", "RobExtremes", "MKpower", "MKclass"))
```


```{r}
## Development Version von GitHub
# install.packages("remotes")
remotes::install_github("stamats/rmx", build_vignettes = TRUE)
```


```{r}
library(ggplot2)
library(MKdescr)
library(distrMod)
library(qqplotr)
library(RobLox)
library(gridExtra)
library(MKinfer)
library(ROptEst)
library(RobExtremes)
library(MKpower)
library(MKclass)
library(rmx)
library(MASS)
library(boot)
library(parallel)
```


## 5.1 Einführung

## 5.2 Punktschätzer

```{r}
ITSDaten <- read.csv2(file = "ITSDaten.csv", fileEncoding = "utf8")
## biasfrei und effizient
table(ITSDaten$Leberversagen)/nrow(ITSDaten)
```


```{r}
## biasfrei und effizient
mean(ITSDaten$Temperatur[-398])
## biasfrei
sd(ITSDaten$Temperatur[-398])
```


```{r}
pnorm(10, mean = 37.7, sd = 1.2)
```


```{r}
fitdistr(ITSDaten$Temperatur[-398], densfun = "normal")
```


```{r}
## Ausgabeoption ändern
distrModOptions(show.details = "minimal")
## Anlegen des Modells
Modell <- NormLocationScaleFamily()
## ML-Schätzung
MLEstimator(ITSDaten$Temperatur[-398], Modell)
```


```{r}
hist(ITSDaten$Temperatur[-398], breaks = seq(from = 33, to = 42, by = 0.5),
     main = "Maximale Körpertemperatur", ylab = "Dichte", freq = FALSE)
lines(density(ITSDaten$Temperatur[-398]))
curve(dnorm(x, mean = 37.7, sd = 1.2), col = "darkred", from = 33, to = 42,
      n = 501, add = TRUE, lwd = 2)
legend("topright", fill = "darkred", legend = "Geschätztes Modell")
```


```{r}
ggplot(ITSDaten[-398,], aes(x=Temperatur)) +
  geom_histogram(aes(y=..density..), binwidth = 0.5, fill = "darkgrey") +
  geom_density(color = "orange") + ylab("Dichte") +
  stat_function(fun = dnorm, args = list(mean = 37.7, sd = 1.2),
                color = "darkred", lwd = 2) +
  annotate("text", x = 40, y = 0.31, col = "darkred",
           label = "Geschätztes Modell")+
  ggtitle("Maximale Körpertemperatur")
```


```{r}
ggplot(ITSDaten[-398,], aes(sample = Temperatur)) + 
  qqplotr::stat_pp_band(dparams = list(mean = 37.7, sd = 1.2)) + 
  qqplotr::stat_pp_point(dparams = list(mean = 37.7, sd = 1.2)) + 
  qqplotr::stat_pp_line() + 
  xlab("Modell für Maximale Körpertemperatur") + 
  ylab("Beobachtete Maximale Körpertemperatur") + 
  ggtitle("pp-Plot für Norm(37.7, 1.2)")
```


```{r}
qqnorm(ITSDaten$Temperatur[-398], main = "qq-Plot für die Normalverteilung",
       ylab = "Maximale Körpertemperatur")
qqline(ITSDaten$Temperatur[-398])
```


```{r}
ggplot(ITSDaten[-398,], aes(sample = Temperatur)) + 
  stat_qq() + ggplot2::stat_qq_line() +
  xlab("Theoretische Quantile") + 
  ylab("Beobachtete Maximale Körpertemperatur") + 
  ggtitle("qq-Plot für die Normalverteilung")
```


```{r}
ggplot(ITSDaten[-398,], aes(sample = Temperatur)) + 
  stat_qq(dparams = list(mean = 37.7, sd = 1.2)) + 
  ggplot2::stat_qq_line(dparams = list(mean = 37.7, sd = 1.2)) +
  geom_abline(slope = 1, color = "blue") +
  xlab("Modell für Maximale Körpertemperatur") + 
  ylab("Beobachtete Maximale Körpertemperatur") + 
  ggtitle("qq-Plot für Norm(37.7, 1.2)")
```


```{r}
qqplot(ITSDaten$Temperatur[-398], Norm(mean = 37.7, sd = 1.2),
       xlab = "Maximale Körpertemperatur",
       main = "qq-Plot für Norm(37.7, 1.2)")
```


```{r}
ggplot(ITSDaten[-398,], aes(sample = Temperatur)) + 
  qqplotr::stat_qq_band(dparams = list(mean = 37.7, sd = 1.2), identity = TRUE) + 
  qqplotr::stat_qq_point(dparams = list(mean = 37.7, sd = 1.2)) + 
  qqplotr::stat_qq_line(dparams = list(mean = 37.7, sd = 1.2), identity = TRUE) + 
  xlab("Modell für Maximale Körpertemperatur") + 
  ylab("Beobachtete Maximale Körpertemperatur") + 
  ggtitle("qq-Plot für Norm(37.7, 1.2)")
```


```{r, fig.height=10, fig.width=10}
par(mfrow=c(3,3))
for(i in 1:9){
  x <- rnorm(499)
  qqnorm(x)
  qqline(x)
}
```


```{r}
median(ITSDaten$Temperatur)
mad(ITSDaten$Temperatur)
sIQR(ITSDaten$Temperatur)
```


```{r}
Modell <- NormLocationScaleFamily()
CvMMDEstimator(ITSDaten$Temperatur[-398], Modell)
```


```{r}
KolmogorovMDEstimator(ITSDaten$Temperatur[-398], Modell)
```


```{r}
## ML-Schätzer
MLEstimator(ITSDaten$Temperatur, Modell)
## CvM-MD-Schätzer
CvMMDEstimator(ITSDaten$Temperatur, Modell)
## KS-MD-Schätzer
KolmogorovMDEstimator(ITSDaten$Temperatur, Modell)
```


```{r}
roblox(ITSDaten$Temperatur, eps.lower = 1/500, eps.upper = 0.05, k = 3)
```


```{r}
res.rmx <- rmx(ITSDaten$Temperatur, model = "norm", 
               eps.lower = 1/500, eps.upper = 0.05)
res.rmx
```


```{r}
summary(res.rmx)
```


```{r}
outlier(res.rmx)
getOutliers(res.rmx)
```


```{r, fig.height=14}
gg1 <- ppPlot(res.rmx)
gg2 <- qqPlot(res.rmx)
gg3 <- dPlot(res.rmx)
grid.arrange(gg1, gg2, gg3, nrow = 1)
```


```{r, eval=FALSE}
path.package("ROptEst")
```


```{r, eval=FALSE}
vignette("rmx")
```


```{r}
qnorm(0.95)
```


```{r}
pnorm(3.3)
```


```{r}
Bili <- round(ITSDaten$Bilirubin, 1)
```


```{r}
quantile(Bili[ITSDaten$Leberversagen == 0], probs = 0.95)
perfMeasures(pred = Bili, truth = ITSDaten$Leberversagen, 
             namePos = 1, cutoff = 49.615, measures = c("SENS", "SPEC"))
```


```{r}
mean(log(Bili[ITSDaten$Leberversagen == 0]))
sd(log(Bili[ITSDaten$Leberversagen == 0]))
qlnorm(0.95, meanlog = 2.774, sdlog = 0.604)
perfMeasures(pred = Bili, truth = ITSDaten$Leberversagen, 
             namePos = 1, cutoff = 43.27, measures = c("SENS", "SPEC"))
```


```{r}
optCutoff(pred = Bili, truth = ITSDaten$Leberversagen, namePos = 1)
optCutoff(pred = Bili, truth = ITSDaten$Leberversagen, 
          namePos = 1, perfMeasure = "BACC")
perfMeasures(pred = Bili, truth = ITSDaten$Leberversagen, 
             namePos = 1, cutoff = 28.4, measures = c("SENS", "SPEC"))
```


```{r cache = TRUE}
B <- 1000
n0 <- sum(ITSDaten$Leberversagen == 0)
ind0 <- which(ITSDaten$Leberversagen == 0)
n1 <- sum(ITSDaten$Leberversagen == 1)
ind1 <- which(ITSDaten$Leberversagen == 1)
cutoffs <- numeric(B)
for(i in 1:B){
  auswahl0 <- sample(ind0, n0, replace = TRUE)
  auswahl1 <- sample(ind1, n1, replace = TRUE)
  BS.data <- ITSDaten[c(auswahl0, auswahl1),]
  cutoffs[i] <- optCutoff(pred = round(BS.data$Bilirubin, 1), 
                          truth = BS.data$Leberversagen, 
                          namePos = 1)[1]
}
summary(cutoffs)
```


```{r}
perfMeasures(pred = Bili, truth = ITSDaten$Leberversagen, 
             namePos = 1, cutoff = mean(cutoffs), 
             measures = c("SENS", "SPEC"))
```


```{r}
## Mehr Gewicht auf Sensitivität
optCutoff(pred = Bili, truth = ITSDaten$Leberversagen, 
          namePos = 1, perfMeasure = "WACC", wACC = 0.75)
perfMeasures(pred = Bili, truth = ITSDaten$Leberversagen, 
             namePos = 1, cutoff = 17.7, measures = c("SENS", "SPEC"))
## Mehr Gewicht auf Spezifität
optCutoff(pred = Bili, truth = ITSDaten$Leberversagen, 
          namePos = 1, perfMeasure = "WACC", wACC = 0.25)
perfMeasures(pred = Bili, truth = ITSDaten$Leberversagen, 
             namePos = 1, cutoff = 53.3, measures = c("SENS", "SPEC"))
```


```{r}
stump <- decisionStump(pred = Bili, truth = ITSDaten$Leberversagen, 
                       namePos = 1)
stump
```


```{r}
predict(stump, newdata = c(4.3, 10.1, 17.4, 28.4, 28.5, 71.0, 93.1))
```


```{r}
perfScores(pred = Bili, truth = ITSDaten$Leberversagen, namePos = 1, 
           scores = "AUC")
perfScores(pred = Bili, truth = ITSDaten$Leberversagen, namePos = 1, 
           scores = c("AUC", "BS"), transform = TRUE)
```


## 5.2 Konfidenzintervalle

```{r}
meanCI(ITSDaten$Temperatur[-398])
```


```{r}
t.test(ITSDaten$Temperatur[-398])$conf.int
```


```{r}
qt(1-0.05/2, df = 499-1)
qnorm(1-0.05/2)
```


```{r}
## ML-Schätzer
ML <- fitdistr(ITSDaten$Temperatur[-398], densfun = "normal")
## Approximatives Konfidenzintervall
confint(ML)
```


```{r}
## Modell
Modell <- NormLocationScaleFamily()
## ML-Schäter
ML2 <- MLEstimator(ITSDaten$Temperatur[-398], Modell)
## Approximatives Konfidenzintervall
confint(ML2)
```


```{r}
## nur Standardabweiung
sdCI(ITSDaten$Temperatur[-398])
## Mittelwert und Standardabweichung
normCI(ITSDaten$Temperatur[-398])
```


```{r}
normCI(ITSDaten$Temperatur[-398], boot = TRUE)
```


```{r}
## Häufigkeit von Leberversagen
table(ITSDaten$Leberversagen)
## Wilson-Intervall
binomCI(x = 20, n = 500)
## Clopper-Pearson-Intervall
binomCI(x = 20, n = 500, method = "clopper-pearson")
## Agresti-Coull-Intervall
binomCI(x = 20, n = 500, method = "agresti-coull")
```


```{r}
## ohne Stetigkeitskorrektur
binomCI(x = 20, n = 500, method = "wald")
## mit Stetigkeitskorrektur
binomCI(x = 20, n = 500, method = "wald-cc")
```


```{r}
binomCI(x = 20, n = 500, method = "boot")
```


```{r}
## Bernoulli-Modell
Modell <- BinomFamily(size = 1)
## ML-Schätzer
MLp <- MLEstimator(ITSDaten$Leberversagen, Modell)
MLp
## Konfidenzintervall
confint(MLp)
```


```{r}
## Exaktes Konfidenzintervall für den Median
medianCI(ITSDaten$Temperatur)
## Exaktes Konfidenzintervall für den MAD
madCI(ITSDaten$Temperatur)
```


```{r}
## Asymptotisches Konfidenzintervall für den Median
medianCI(ITSDaten$Temperatur, method = "asymptotic")
## Asymptotisches Konfidenzintervall für den MAD
madCI(ITSDaten$Temperatur, method = "asymptotic")
```


```{r}
## Bootstrap-Konfidenzintervall für den Median
medianCI(ITSDaten$Temperatur, method = "boot")
## Bootstrap-Konfidenzintervall für den MAD
madCI(ITSDaten$Temperatur, method = "boot")
```


```{r}
## Modell
Modell <- NormLocationScaleFamily()
## CvM-MD-Schätzer inkl. Varianz
MD <- CvMMDEstimator(ITSDaten$Temperatur, Modell)
## 95%-Konfidenzintervall
confint(MD)
```


```{r}
## Modell
Modell <- BinomFamily(size = 1)
## CvM-MD-Schätzer inkl. Varianz
MDp <- CvMMDEstimator(ITSDaten$Leberversagen, Modell)
## 95%-Konfidenzintervall
confint(MDp)
```


```{r}
## x: Vektor der Beobachtungen
## i: Vektor der Indizes der Bootstrap-Stichprobe
KSMDEst <- function(x, i){
  estimate(KolmogorovMDEstimator(x[i], ParamFamily = NormLocationScaleFamily()))
}
```


```{r cache=TRUE}
## Bootstrap-Schätzungen
boot.out <- boot(ITSDaten$Temperatur, statistic = KSMDEst, R = 999)
## Bootstrap-Konfidenzintervalle
boot.ci(boot.out, index = 1)
boot.ci(boot.out, index = 2)
```


```{r}
ALest <- roblox(ITSDaten$Temperatur, eps.lower = 1/500, 
                eps.upper = 0.05, k = 3)
confint(ALest)
```



```{r}
confint(ALest, symmetricBias())
```


```{r}
RMXest <- rmx(ITSDaten$Temperatur, model = "norm", 
               eps.lower = 1/500, eps.upper = 0.05)
confint(RMXest)
confint(RMXest, method = "as.bias")
```


```{r}
confint(RMXest, method = "boot")
```


```{r}
## x: Vektor der Beobachtungen
## i: Vektor der Indizes der Bootstrap-Stichprobe
RMXEst <- function(x, i){
  res <- roblox(x[i], eps.lower = 1/500, eps.upper = 0.05, k = 3)
  c(estimate(res), diag(asvar(res)))
}
```


```{r cache = TRUE}
## Bootstrap-Schätzungen
boot.out <- boot(ITSDaten$Temperatur, statistic = RMXEst, R = 999)
## Bootstrap-Konfidenzintervall für den Mittelwert
boot.ci(boot.out, index = c(1,3))
## Bootstrap-Konfidenzintervall für die Standardabweichung
boot.ci(boot.out, index = c(2,4))
```


```{r}
ITSDaten.nachHause <- ITSDaten[ITSDaten$Ergebnis == "nach Hause",]
```


```{r, cache=TRUE}
Modell <- GammaFamily()
MLest <- MLEstimator(ITSDaten.nachHause$SAPS.II, Modell)
MLest
MDest <- CvMMDEstimator(ITSDaten.nachHause$SAPS.II, Modell)
MDest
RMXest <- roptest(ITSDaten.nachHause$SAPS.II, Modell, 
                  eps.lower = 0, eps.upper = 0.05, steps = 3)
RMXest
```


```{r, fig.width=9}
gg1 <- ggplot(ITSDaten.nachHause, aes(sample = SAPS.II)) + 
  qqplotr::stat_pp_band(dparams = list(scale = 5.58, shape = 7.0), 
                        distribution = "gamma") + 
  qqplotr::stat_pp_point(dparams = list(scale = 5.58, shape = 7.0),
                         distribution = "gamma") +
  qqplotr::stat_pp_line() + 
  xlab("Kumulative Wahrscheinlichkeit des Modells") + 
  ylab("Beobachtete kumulative Wahrscheinlichkeit") + 
  ggtitle("pp-Plot: ML-Schätzer")
gg2 <- ggplot(ITSDaten.nachHause, aes(sample = SAPS.II)) + 
  qqplotr::stat_qq_band(dparams = list(scale = 5.58, shape = 7.0), 
                        distribution = "gamma", identity = TRUE) + 
  qqplotr::stat_qq_point(dparams = list(scale = 5.58, shape = 7.0),
                         distribution = "gamma") + 
  qqplotr::stat_qq_line(dparams = list(scale = 5.58, shape = 7.0), 
                        distribution = "gamma", identity = TRUE) + 
  xlab("Modell für SAPS-II") + 
  ylab("Beobachtete SAPS-II Scores") + 
  ggtitle("qq-Plot: ML-Schätzer")
grid.arrange(gg1, gg2, nrow = 1)
```


```{r, fig.width=9}
gg1 <- ggplot(ITSDaten.nachHause, aes(sample = SAPS.II)) + 
  qqplotr::stat_pp_band(dparams = list(scale = 6.03, shape = 6.46), 
                        distribution = "gamma") + 
  qqplotr::stat_pp_point(dparams = list(scale = 6.03, shape = 6.46),
                         distribution = "gamma") +
  qqplotr::stat_pp_line() + 
  xlab("Kumulative Wahrscheinlichkeit des Modells") + 
  ylab("Beobachtete kumulative Wahrscheinlichkeit") + 
  ggtitle("pp-Plot: CvM-MD-Schätzer")
gg2 <- ggplot(ITSDaten.nachHause, aes(sample = SAPS.II)) + 
  qqplotr::stat_qq_band(dparams = list(scale = 6.03, shape = 6.46), 
                        distribution = "gamma", identity = TRUE) + 
  qqplotr::stat_qq_point(dparams = list(scale = 6.03, shape = 6.46),
                         distribution = "gamma") + 
  qqplotr::stat_qq_line(dparams = list(scale = 6.03, shape = 6.46), 
                        distribution = "gamma", identity = TRUE) + 
  xlab("Modell für SAPS-II") + 
  ylab("Beobachtete SAPS-II Scores") + 
  ggtitle("qq-Plot: CvM-MD-Schätzer")
grid.arrange(gg1, gg2, nrow = 1)
```


```{r, fig.width=9}
gg1 <- ggplot(ITSDaten.nachHause, aes(sample = SAPS.II)) + 
  qqplotr::stat_pp_band(dparams = list(scale = 5.90, shape = 6.66), 
                        distribution = "gamma") + 
  qqplotr::stat_pp_point(dparams = list(scale = 5.90, shape = 6.66),
                         distribution = "gamma") +
  qqplotr::stat_pp_line() + 
  xlab("Kumulative Wahrscheinlichkeit des Modells") + 
  ylab("Beobachtete kumulative Wahrscheinlichkeit") + 
  ggtitle("pp-Plot: RMX-Schätzer")
gg2 <- ggplot(ITSDaten.nachHause, aes(sample = SAPS.II)) + 
  qqplotr::stat_qq_band(dparams = list(scale = 5.90, shape = 6.66), 
                        distribution = "gamma", identity = TRUE) + 
  qqplotr::stat_qq_point(dparams = list(scale = 5.90, shape = 6.66),
                         distribution = "gamma") + 
  qqplotr::stat_qq_line(dparams = list(scale = 5.90, shape = 6.66), 
                        distribution = "gamma", identity = TRUE) + 
  xlab("Modell für SAPS-II") + 
  ylab("Beobachtete SAPS-II Scores") + 
  ggtitle("qq-Plot: RMX-Schätzer")
grid.arrange(gg1, gg2, nrow = 1)
```


```{r}
ggplot(ITSDaten.nachHause, aes(x=SAPS.II)) +
  geom_histogram(aes(y=..density..), binwidth = 5, fill = "darkgrey") +
  geom_density(color = "orange") + ylab("Dichte") +
  stat_function(fun = dgamma, args = list(scale = 5.58, shape = 7.0),
                color = "darkred", lwd = 1.5) +
  stat_function(fun = dgamma, args = list(scale = 6.03, shape = 6.46),
                color = "darkblue", lwd = 1.5) +
  stat_function(fun = dgamma, args = list(scale = 5.90, shape = 6.66),
                color = "darkgreen", lwd = 1.5) +
  annotate("text", x = 70, y = 0.035, col = "darkred",
           label = "ML-Schätzer") +
  annotate("text", x = 70, y = 0.0325, col = "darkblue",
           label = "CvM-MD-Schätzer") +
  annotate("text", x = 70, y = 0.030, col = "darkgreen",
           label = "RMX-Schätzer") +
  ggtitle("Vergleich der geschätzten Modelle")
```


```{r}
distrMod::confint(MLest)
distrMod::confint(MDest)
distrMod::confint(RMXest)
```


```{r}
## x: Vektor der Beobachtungen
## i: Vektor der Indizes der Bootstrap-Stichprobe
MLEst <- function(x, i){
  res <- MLEstimator(x[i], ParamFamily = GammaFamily())
  c(estimate(res), diag(asvar(res)))
}
MDEst <- function(x, i){
  res <- CvMMDEstimator(x[i], ParamFamily = GammaFamily())
  c(estimate(res), diag(asvar(res)))
}
RMXEst <- function(x, i){
  res <- roptest(x[i], ParamFamily = GammaFamily(), 
                 eps.lower = 0, eps.upper = 0.05, steps = 3)
  c(estimate(res), diag(asvar(res)))
}
```


```{r}
nr.cpus <- detectCores()-1
```


```{r, cache=TRUE}
## Bootstrap-Schätzungen
boot.out <- boot(ITSDaten$Temperatur, statistic = MLEst, R = 999,
                 parallel = "multicore", ncpus = nr.cpus)
## Bootstrap-Konfidenzintervall für scale
boot.ci(boot.out, index = c(1,3))
## Bootstrap-Konfidenzintervall für shape
boot.ci(boot.out, index = c(2,4))
```


```{r, cache=TRUE}
## Bootstrap-Schätzungen
boot.out <- boot(ITSDaten.nachHause$SAPS.II, statistic = MDEst, R = 999,
                 parallel = "multicore", ncpus = nr.cpus)
## Bootstrap-Konfidenzintervall für scale
boot.ci(boot.out, index = c(1,3))
## Bootstrap-Konfidenzintervall für shape
boot.ci(boot.out, index = c(2,4))
```


```{r, cache=TRUE, eval=FALSE}
## Bootstrap-Schätzungen
boot.out <- boot(ITSDaten.nachHause$SAPS.II, statistic = RMXEst, R = 999,
                 parallel = "multicore", ncpus = nr.cpus)
## Bootstrap-Konfidenzintervall für scale
boot.ci(boot.out, index = c(1,3))
## Bootstrap-Konfidenzintervall für shape
boot.ci(boot.out, index = c(2,4))
```


```{r}
qnorm(0.975)
```


```{r}
## Werte für p
p <- seq(from = 0.01, to = 0.99, length = 100)
## Standardabweichung
SD <- sqrt(p*(1-p))
## Grafische Darstellung
DF <- data.frame(p, SD)
ggplot(DF, aes(x = p, y = SD)) + geom_line() + 
  ylab(expression(sqrt(p*(1-p)))) + 
  xlab("p") + ggtitle("Standardabweichung von Bernoulli(p)")
```


```{r, fig.width = 8}
## Stichprobengröße
n <- seq(60, 10000, by = 20)
## Maximaler Schätzfehler
maxFehler <- 97.5/sqrt(n)
## Grafische Darstellung
DF <- data.frame(n, maxFehler)
ggplot(DF, aes(x = n, y = maxFehler)) + geom_line() + ylab("Prozent [%]") + 
  xlab("Stichprobengröße") + ggtitle("Maximaler Schätzfehler")
```


```{r}
## ohne Stetigkeitskorrektur
ssize.propCI(0.5, width = 0.062, method = "wald")
## mit Stetigkeitskorrektur
ssize.propCI(0.5, width = 0.062, method = "wald-cc")
## Clopper-Pearson
ssize.propCI(0.5, width = 0.062, method = "clopper-pearson")
## Agresti-Coull
ssize.propCI(0.5, width = 0.062, method = "agresti-coull")
```


```{r}
## ohne Stetigkeitskorrektur
ssize.propCI(0.5, width = 0.0088, method = "wald")
## mit Stetigkeitskorrektur
ssize.propCI(0.5, width = 0.0088, method = "wald-cc")
```

